# XmlPSProfile Workflow
name: Test Runs

on:
  push:
    # Allowed branches
    branches: 
      - dev
      - beta
      - master
    # Ignored Files and paths
    paths-ignore:
      - '**.md'
      - '**.log'
      - '**.xsd'
      - '**.sql' # If the VM does not have a sql db then it will not execute .sql queries
      - '.gitignore'
      - '**.txt'
      - '**.csv'

jobs:
  Run-Test:
    runs-on: windows-latest # On windows VM

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      shell: pwsh
      run: |
        Write-Host "`nLoading Profile";
        .\Profile.ps1 -BuildPath:$(".\Tests\Profile.xml");
        Write-Host "`nRunning Test Scripts";
        D:\a\XmlPSProfile\XmlPSProfile\Tests\InitTestScripts.ps1;

