# This is a basic workflow to help you get started with Actions

name: Loading Profile

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - dev
      - beta
      - master
    paths-ignore:
      - '*.md'
      - '*.log'
      - '*.xsd'
      - '*.sql' # If the VM does not have a sql db then it will not execute .sql queries
      - '.gitignore'
      - '.txt'
      - '.csv'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Running powershell profile
      run: |
        .\Profile.ps1 -IsBuild:$true;
      
