# Auto tagging
# refs: https://github.com/temelj/pipeline-gitver-tag-test/blob/master/azure-pipelines.yml
# Initiates auto tag
name: Tagging

on:
  push:
    # Will only tag in the dev branch
    branches: 
      - dev
    # Only files that will trigger a tag are app powershell scripts
    # powershell scripts in the StartScipts are considered config
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.json'
      - '**.xml'
      - '**.sql'
      - '**.xsd'
      - '**.txt'
      - '**.log'
      - '.gitignore'
      - 'StartScripts/**'
      - 'Cache/**'
      - 'Tests/Scripts/**' # Do not tag any changes from the test scripts

jobs:
  Tag-Commit:
    runs-on: windows-latest # On windows VM

    steps:
    - uses: actions/checkout@v2

    - name: Retrieve all branches and tags
      shell: pwsh
      run: |
        git fetch --prune --unshallow --tags

    - name: Set new tag
      shell: pwsh
      run: |
        .\Profile.ps1 -BuildPath:$(".\Tests\Profile.xml") -Silent:$true;
        $env:GIT_REDIRECT_STDERR = '2>&1';
        .\Functions\DetermineTagType.ps1 -Push:$true;

