# XmlPSProfile Workflow
name: Testing

on:
  push:
    # Allowed branches
    branches: 
      - dev
      - beta
      - master
      - 'tests-*'
    # Ignored Files and paths
    paths-ignore:
      - '**.md'
      - '**.log'
      - '**.xsd'
      - '**.sql' # If the VM does not have a sql db then it will not execute .sql queries
      - '.gitignore'
      - '**.txt'
      - '**.csv'

jobs:
  # Powershell on Windows
  Powershell-Run-Test-Windows:
    runs-on: windows-latest # On windows VM

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      shell: powershell
      run: |
        Write-Host "`nLoading Profile";
        .\Profile.ps1 -BuildPath:$(".\Tests\Profile.xml");
        Write-Host "`nRunning Test Scripts";
        D:\a\XmlPSProfile\XmlPSProfile\Tests\InitTestScripts.ps1;

  # Powershell 7 on Windows
  Powershell7-Run-Test-Windows:
    runs-on: windows-latest # On windows VM

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      shell: pwsh
      run: |
        Write-Host "`nLoading Profile";
        .\Profile.ps1 -BuildPath:$(".\Tests\Profile.xml");
        Write-Host "`nRunning Test Scripts";
        D:\a\XmlPSProfile\XmlPSProfile\Tests\InitTestScripts.ps1;

  # # Powershell 7 on Ubuntu
  # Powershell7-Run-Test-Ubuntu:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Run tests
  #     shell: pwsh
  #     run: |
  #       Write-Host "`nLoading Profile";
  #       .\Profile.ps1 -BuildPath:$(".\Tests\Profile.xml");
  #       Write-Host "`nRunning Test Scripts";
  #       D:\a\XmlPSProfile\XmlPSProfile\Tests\InitTestScripts.ps1;

  # # Powershell 7 on Ubuntu
  # Powershell7-Run-Test-Mac:
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Run tests
  #     shell: pwsh
  #     run: |
  #       Write-Host "`nLoading Profile";
  #       .\Profile.ps1 -BuildPath:$(".\Tests\Profile.xml");
  #       Write-Host "`nRunning Test Scripts";
  #       D:\a\XmlPSProfile\XmlPSProfile\Tests\InitTestScripts.ps1;

